#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassChung
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PillID")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertd_ChiDinh(d_ChiDinh instance);
    partial void Updated_ChiDinh(d_ChiDinh instance);
    partial void Deleted_ChiDinh(d_ChiDinh instance);
    partial void Insertw_NhanDangThuoc(w_NhanDangThuoc instance);
    partial void Updatew_NhanDangThuoc(w_NhanDangThuoc instance);
    partial void Deletew_NhanDangThuoc(w_NhanDangThuoc instance);
    partial void Insertd_DangThuoc(d_DangThuoc instance);
    partial void Updated_DangThuoc(d_DangThuoc instance);
    partial void Deleted_DangThuoc(d_DangThuoc instance);
    partial void Insertd_HinhAnhThuocChiTiet(d_HinhAnhThuocChiTiet instance);
    partial void Updated_HinhAnhThuocChiTiet(d_HinhAnhThuocChiTiet instance);
    partial void Deleted_HinhAnhThuocChiTiet(d_HinhAnhThuocChiTiet instance);
    partial void Insertd_HinhDang(d_HinhDang instance);
    partial void Updated_HinhDang(d_HinhDang instance);
    partial void Deleted_HinhDang(d_HinhDang instance);
    partial void Insertd_HoatChat(d_HoatChat instance);
    partial void Updated_HoatChat(d_HoatChat instance);
    partial void Deleted_HoatChat(d_HoatChat instance);
    partial void Insertd_HoatChatGoc(d_HoatChatGoc instance);
    partial void Updated_HoatChatGoc(d_HoatChatGoc instance);
    partial void Deleted_HoatChatGoc(d_HoatChatGoc instance);
    partial void Insertd_LoaiRanh(d_LoaiRanh instance);
    partial void Updated_LoaiRanh(d_LoaiRanh instance);
    partial void Deleted_LoaiRanh(d_LoaiRanh instance);
    partial void Insertd_LoaiViThuoc(d_LoaiViThuoc instance);
    partial void Updated_LoaiViThuoc(d_LoaiViThuoc instance);
    partial void Deleted_LoaiViThuoc(d_LoaiViThuoc instance);
    partial void Insertd_MauSac(d_MauSac instance);
    partial void Updated_MauSac(d_MauSac instance);
    partial void Deleted_MauSac(d_MauSac instance);
    partial void Insertd_Thuoc(d_Thuoc instance);
    partial void Updated_Thuoc(d_Thuoc instance);
    partial void Deleted_Thuoc(d_Thuoc instance);
    partial void Insertr_HoatChat_HoatChatGoc(r_HoatChat_HoatChatGoc instance);
    partial void Updater_HoatChat_HoatChatGoc(r_HoatChat_HoatChatGoc instance);
    partial void Deleter_HoatChat_HoatChatGoc(r_HoatChat_HoatChatGoc instance);
    partial void Insertr_HoatChatGoc_ChiDinh(r_HoatChatGoc_ChiDinh instance);
    partial void Updater_HoatChatGoc_ChiDinh(r_HoatChatGoc_ChiDinh instance);
    partial void Deleter_HoatChatGoc_ChiDinh(r_HoatChatGoc_ChiDinh instance);
    partial void Insertr_Thuoc_MauSac(r_Thuoc_MauSac instance);
    partial void Updater_Thuoc_MauSac(r_Thuoc_MauSac instance);
    partial void Deleter_Thuoc_MauSac(r_Thuoc_MauSac instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::ClassChung.Properties.Settings.Default.PillIDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<d_ChiDinh> d_ChiDinhs
		{
			get
			{
				return this.GetTable<d_ChiDinh>();
			}
		}
		
		public System.Data.Linq.Table<w_NhanDangThuoc> w_NhanDangThuocs
		{
			get
			{
				return this.GetTable<w_NhanDangThuoc>();
			}
		}
		
		public System.Data.Linq.Table<d_DangThuoc> d_DangThuocs
		{
			get
			{
				return this.GetTable<d_DangThuoc>();
			}
		}
		
		public System.Data.Linq.Table<d_HinhAnhThuocChiTiet> d_HinhAnhThuocChiTiets
		{
			get
			{
				return this.GetTable<d_HinhAnhThuocChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<d_HinhDang> d_HinhDangs
		{
			get
			{
				return this.GetTable<d_HinhDang>();
			}
		}
		
		public System.Data.Linq.Table<d_HoatChat> d_HoatChats
		{
			get
			{
				return this.GetTable<d_HoatChat>();
			}
		}
		
		public System.Data.Linq.Table<d_HoatChatGoc> d_HoatChatGocs
		{
			get
			{
				return this.GetTable<d_HoatChatGoc>();
			}
		}
		
		public System.Data.Linq.Table<d_LoaiRanh> d_LoaiRanhs
		{
			get
			{
				return this.GetTable<d_LoaiRanh>();
			}
		}
		
		public System.Data.Linq.Table<d_LoaiViThuoc> d_LoaiViThuocs
		{
			get
			{
				return this.GetTable<d_LoaiViThuoc>();
			}
		}
		
		public System.Data.Linq.Table<d_MauSac> d_MauSacs
		{
			get
			{
				return this.GetTable<d_MauSac>();
			}
		}
		
		public System.Data.Linq.Table<d_Thuoc> d_Thuocs
		{
			get
			{
				return this.GetTable<d_Thuoc>();
			}
		}
		
		public System.Data.Linq.Table<r_HoatChat_HoatChatGoc> r_HoatChat_HoatChatGocs
		{
			get
			{
				return this.GetTable<r_HoatChat_HoatChatGoc>();
			}
		}
		
		public System.Data.Linq.Table<r_HoatChatGoc_ChiDinh> r_HoatChatGoc_ChiDinhs
		{
			get
			{
				return this.GetTable<r_HoatChatGoc_ChiDinh>();
			}
		}
		
		public System.Data.Linq.Table<r_Thuoc_MauSac> r_Thuoc_MauSacs
		{
			get
			{
				return this.GetTable<r_Thuoc_MauSac>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_ChiDinh")]
	public partial class d_ChiDinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDChiDinh;
		
		private string _TenChiDinh;
		
		private string _MoTa;
		
		private EntitySet<r_HoatChatGoc_ChiDinh> _r_HoatChatGoc_ChiDinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChiDinhChanging(int value);
    partial void OnIDChiDinhChanged();
    partial void OnTenChiDinhChanging(string value);
    partial void OnTenChiDinhChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public d_ChiDinh()
		{
			this._r_HoatChatGoc_ChiDinhs = new EntitySet<r_HoatChatGoc_ChiDinh>(new Action<r_HoatChatGoc_ChiDinh>(this.attach_r_HoatChatGoc_ChiDinhs), new Action<r_HoatChatGoc_ChiDinh>(this.detach_r_HoatChatGoc_ChiDinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChiDinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDChiDinh
		{
			get
			{
				return this._IDChiDinh;
			}
			set
			{
				if ((this._IDChiDinh != value))
				{
					this.OnIDChiDinhChanging(value);
					this.SendPropertyChanging();
					this._IDChiDinh = value;
					this.SendPropertyChanged("IDChiDinh");
					this.OnIDChiDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChiDinh", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenChiDinh
		{
			get
			{
				return this._TenChiDinh;
			}
			set
			{
				if ((this._TenChiDinh != value))
				{
					this.OnTenChiDinhChanging(value);
					this.SendPropertyChanging();
					this._TenChiDinh = value;
					this.SendPropertyChanged("TenChiDinh");
					this.OnTenChiDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(500)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_ChiDinh_r_HoatChatGoc_ChiDinh", Storage="_r_HoatChatGoc_ChiDinhs", ThisKey="IDChiDinh", OtherKey="IDChiDinh")]
		public EntitySet<r_HoatChatGoc_ChiDinh> r_HoatChatGoc_ChiDinhs
		{
			get
			{
				return this._r_HoatChatGoc_ChiDinhs;
			}
			set
			{
				this._r_HoatChatGoc_ChiDinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_r_HoatChatGoc_ChiDinhs(r_HoatChatGoc_ChiDinh entity)
		{
			this.SendPropertyChanging();
			entity.d_ChiDinh = this;
		}
		
		private void detach_r_HoatChatGoc_ChiDinhs(r_HoatChatGoc_ChiDinh entity)
		{
			this.SendPropertyChanging();
			entity.d_ChiDinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.w_NhanDangThuoc")]
	public partial class w_NhanDangThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDNhanDang;
		
		private int _IDThuoc;
		
		private bool _CoKhacDau;
		
		private string _KhacDauMatTruoc;
		
		private string _KhacDauMatSau;
		
		private int _IDHinhDang;
		
		private int _IDDangThuoc;
		
		private System.Nullable<int> _IDLoaiViThuoc;
		
		private System.Nullable<int> _IDLoaiRanh;
		
		private string _MaHinh;
		
		private EntitySet<d_HinhAnhThuocChiTiet> _d_HinhAnhThuocChiTiets;
		
		private EntityRef<d_DangThuoc> _d_DangThuoc;
		
		private EntityRef<d_HinhDang> _d_HinhDang;
		
		private EntityRef<d_LoaiRanh> _d_LoaiRanh;
		
		private EntityRef<d_LoaiViThuoc> _d_LoaiViThuoc;
		
		private EntityRef<d_Thuoc> _d_Thuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNhanDangChanging(int value);
    partial void OnIDNhanDangChanged();
    partial void OnIDThuocChanging(int value);
    partial void OnIDThuocChanged();
    partial void OnCoKhacDauChanging(bool value);
    partial void OnCoKhacDauChanged();
    partial void OnKhacDauMatTruocChanging(string value);
    partial void OnKhacDauMatTruocChanged();
    partial void OnKhacDauMatSauChanging(string value);
    partial void OnKhacDauMatSauChanged();
    partial void OnIDHinhDangChanging(int value);
    partial void OnIDHinhDangChanged();
    partial void OnIDDangThuocChanging(int value);
    partial void OnIDDangThuocChanged();
    partial void OnIDLoaiViThuocChanging(System.Nullable<int> value);
    partial void OnIDLoaiViThuocChanged();
    partial void OnIDLoaiRanhChanging(System.Nullable<int> value);
    partial void OnIDLoaiRanhChanged();
    partial void OnMaHinhChanging(string value);
    partial void OnMaHinhChanged();
    #endregion
		
		public w_NhanDangThuoc()
		{
			this._d_HinhAnhThuocChiTiets = new EntitySet<d_HinhAnhThuocChiTiet>(new Action<d_HinhAnhThuocChiTiet>(this.attach_d_HinhAnhThuocChiTiets), new Action<d_HinhAnhThuocChiTiet>(this.detach_d_HinhAnhThuocChiTiets));
			this._d_DangThuoc = default(EntityRef<d_DangThuoc>);
			this._d_HinhDang = default(EntityRef<d_HinhDang>);
			this._d_LoaiRanh = default(EntityRef<d_LoaiRanh>);
			this._d_LoaiViThuoc = default(EntityRef<d_LoaiViThuoc>);
			this._d_Thuoc = default(EntityRef<d_Thuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhanDang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDNhanDang
		{
			get
			{
				return this._IDNhanDang;
			}
			set
			{
				if ((this._IDNhanDang != value))
				{
					this.OnIDNhanDangChanging(value);
					this.SendPropertyChanging();
					this._IDNhanDang = value;
					this.SendPropertyChanged("IDNhanDang");
					this.OnIDNhanDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThuoc", DbType="Int NOT NULL")]
		public int IDThuoc
		{
			get
			{
				return this._IDThuoc;
			}
			set
			{
				if ((this._IDThuoc != value))
				{
					if (this._d_Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDThuocChanging(value);
					this.SendPropertyChanging();
					this._IDThuoc = value;
					this.SendPropertyChanged("IDThuoc");
					this.OnIDThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoKhacDau", DbType="Bit NOT NULL")]
		public bool CoKhacDau
		{
			get
			{
				return this._CoKhacDau;
			}
			set
			{
				if ((this._CoKhacDau != value))
				{
					this.OnCoKhacDauChanging(value);
					this.SendPropertyChanging();
					this._CoKhacDau = value;
					this.SendPropertyChanged("CoKhacDau");
					this.OnCoKhacDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhacDauMatTruoc", DbType="NVarChar(100)")]
		public string KhacDauMatTruoc
		{
			get
			{
				return this._KhacDauMatTruoc;
			}
			set
			{
				if ((this._KhacDauMatTruoc != value))
				{
					this.OnKhacDauMatTruocChanging(value);
					this.SendPropertyChanging();
					this._KhacDauMatTruoc = value;
					this.SendPropertyChanged("KhacDauMatTruoc");
					this.OnKhacDauMatTruocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhacDauMatSau", DbType="NVarChar(100)")]
		public string KhacDauMatSau
		{
			get
			{
				return this._KhacDauMatSau;
			}
			set
			{
				if ((this._KhacDauMatSau != value))
				{
					this.OnKhacDauMatSauChanging(value);
					this.SendPropertyChanging();
					this._KhacDauMatSau = value;
					this.SendPropertyChanged("KhacDauMatSau");
					this.OnKhacDauMatSauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHinhDang", DbType="Int NOT NULL")]
		public int IDHinhDang
		{
			get
			{
				return this._IDHinhDang;
			}
			set
			{
				if ((this._IDHinhDang != value))
				{
					if (this._d_HinhDang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDHinhDangChanging(value);
					this.SendPropertyChanging();
					this._IDHinhDang = value;
					this.SendPropertyChanged("IDHinhDang");
					this.OnIDHinhDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDangThuoc", DbType="Int NOT NULL")]
		public int IDDangThuoc
		{
			get
			{
				return this._IDDangThuoc;
			}
			set
			{
				if ((this._IDDangThuoc != value))
				{
					if (this._d_DangThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDangThuocChanging(value);
					this.SendPropertyChanging();
					this._IDDangThuoc = value;
					this.SendPropertyChanged("IDDangThuoc");
					this.OnIDDangThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLoaiViThuoc", DbType="Int")]
		public System.Nullable<int> IDLoaiViThuoc
		{
			get
			{
				return this._IDLoaiViThuoc;
			}
			set
			{
				if ((this._IDLoaiViThuoc != value))
				{
					if (this._d_LoaiViThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDLoaiViThuocChanging(value);
					this.SendPropertyChanging();
					this._IDLoaiViThuoc = value;
					this.SendPropertyChanged("IDLoaiViThuoc");
					this.OnIDLoaiViThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLoaiRanh", DbType="Int")]
		public System.Nullable<int> IDLoaiRanh
		{
			get
			{
				return this._IDLoaiRanh;
			}
			set
			{
				if ((this._IDLoaiRanh != value))
				{
					if (this._d_LoaiRanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDLoaiRanhChanging(value);
					this.SendPropertyChanging();
					this._IDLoaiRanh = value;
					this.SendPropertyChanged("IDLoaiRanh");
					this.OnIDLoaiRanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinh", DbType="NVarChar(100)")]
		public string MaHinh
		{
			get
			{
				return this._MaHinh;
			}
			set
			{
				if ((this._MaHinh != value))
				{
					this.OnMaHinhChanging(value);
					this.SendPropertyChanging();
					this._MaHinh = value;
					this.SendPropertyChanged("MaHinh");
					this.OnMaHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="w_NhanDangThuoc_d_HinhAnhThuocChiTiet", Storage="_d_HinhAnhThuocChiTiets", ThisKey="IDNhanDang", OtherKey="IDNhanDang")]
		public EntitySet<d_HinhAnhThuocChiTiet> d_HinhAnhThuocChiTiets
		{
			get
			{
				return this._d_HinhAnhThuocChiTiets;
			}
			set
			{
				this._d_HinhAnhThuocChiTiets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_DangThuoc_w_NhanDangThuoc", Storage="_d_DangThuoc", ThisKey="IDDangThuoc", OtherKey="IDDangThuoc", IsForeignKey=true)]
		public d_DangThuoc d_DangThuoc
		{
			get
			{
				return this._d_DangThuoc.Entity;
			}
			set
			{
				d_DangThuoc previousValue = this._d_DangThuoc.Entity;
				if (((previousValue != value) 
							|| (this._d_DangThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_DangThuoc.Entity = null;
						previousValue.w_NhanDangThuocs.Remove(this);
					}
					this._d_DangThuoc.Entity = value;
					if ((value != null))
					{
						value.w_NhanDangThuocs.Add(this);
						this._IDDangThuoc = value.IDDangThuoc;
					}
					else
					{
						this._IDDangThuoc = default(int);
					}
					this.SendPropertyChanged("d_DangThuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_HinhDang_w_NhanDangThuoc", Storage="_d_HinhDang", ThisKey="IDHinhDang", OtherKey="IDHinhDang", IsForeignKey=true)]
		public d_HinhDang d_HinhDang
		{
			get
			{
				return this._d_HinhDang.Entity;
			}
			set
			{
				d_HinhDang previousValue = this._d_HinhDang.Entity;
				if (((previousValue != value) 
							|| (this._d_HinhDang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_HinhDang.Entity = null;
						previousValue.w_NhanDangThuocs.Remove(this);
					}
					this._d_HinhDang.Entity = value;
					if ((value != null))
					{
						value.w_NhanDangThuocs.Add(this);
						this._IDHinhDang = value.IDHinhDang;
					}
					else
					{
						this._IDHinhDang = default(int);
					}
					this.SendPropertyChanged("d_HinhDang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_LoaiRanh_w_NhanDangThuoc", Storage="_d_LoaiRanh", ThisKey="IDLoaiRanh", OtherKey="IDLoaiRanh", IsForeignKey=true)]
		public d_LoaiRanh d_LoaiRanh
		{
			get
			{
				return this._d_LoaiRanh.Entity;
			}
			set
			{
				d_LoaiRanh previousValue = this._d_LoaiRanh.Entity;
				if (((previousValue != value) 
							|| (this._d_LoaiRanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_LoaiRanh.Entity = null;
						previousValue.w_NhanDangThuocs.Remove(this);
					}
					this._d_LoaiRanh.Entity = value;
					if ((value != null))
					{
						value.w_NhanDangThuocs.Add(this);
						this._IDLoaiRanh = value.IDLoaiRanh;
					}
					else
					{
						this._IDLoaiRanh = default(Nullable<int>);
					}
					this.SendPropertyChanged("d_LoaiRanh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_LoaiViThuoc_w_NhanDangThuoc", Storage="_d_LoaiViThuoc", ThisKey="IDLoaiViThuoc", OtherKey="IDLoaiViThuoc", IsForeignKey=true)]
		public d_LoaiViThuoc d_LoaiViThuoc
		{
			get
			{
				return this._d_LoaiViThuoc.Entity;
			}
			set
			{
				d_LoaiViThuoc previousValue = this._d_LoaiViThuoc.Entity;
				if (((previousValue != value) 
							|| (this._d_LoaiViThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_LoaiViThuoc.Entity = null;
						previousValue.w_NhanDangThuocs.Remove(this);
					}
					this._d_LoaiViThuoc.Entity = value;
					if ((value != null))
					{
						value.w_NhanDangThuocs.Add(this);
						this._IDLoaiViThuoc = value.IDLoaiViThuoc;
					}
					else
					{
						this._IDLoaiViThuoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("d_LoaiViThuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thuoc_w_NhanDangThuoc", Storage="_d_Thuoc", ThisKey="IDThuoc", OtherKey="IDThuoc", IsForeignKey=true)]
		public d_Thuoc d_Thuoc
		{
			get
			{
				return this._d_Thuoc.Entity;
			}
			set
			{
				d_Thuoc previousValue = this._d_Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._d_Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_Thuoc.Entity = null;
						previousValue.w_NhanDangThuocs.Remove(this);
					}
					this._d_Thuoc.Entity = value;
					if ((value != null))
					{
						value.w_NhanDangThuocs.Add(this);
						this._IDThuoc = value.IDThuoc;
					}
					else
					{
						this._IDThuoc = default(int);
					}
					this.SendPropertyChanged("d_Thuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_d_HinhAnhThuocChiTiets(d_HinhAnhThuocChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.w_NhanDangThuoc = this;
		}
		
		private void detach_d_HinhAnhThuocChiTiets(d_HinhAnhThuocChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.w_NhanDangThuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_DangThuoc")]
	public partial class d_DangThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDangThuoc;
		
		private string _TenDangThuoc;
		
		private EntitySet<w_NhanDangThuoc> _w_NhanDangThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDangThuocChanging(int value);
    partial void OnIDDangThuocChanged();
    partial void OnTenDangThuocChanging(string value);
    partial void OnTenDangThuocChanged();
    #endregion
		
		public d_DangThuoc()
		{
			this._w_NhanDangThuocs = new EntitySet<w_NhanDangThuoc>(new Action<w_NhanDangThuoc>(this.attach_w_NhanDangThuocs), new Action<w_NhanDangThuoc>(this.detach_w_NhanDangThuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDangThuoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDangThuoc
		{
			get
			{
				return this._IDDangThuoc;
			}
			set
			{
				if ((this._IDDangThuoc != value))
				{
					this.OnIDDangThuocChanging(value);
					this.SendPropertyChanging();
					this._IDDangThuoc = value;
					this.SendPropertyChanged("IDDangThuoc");
					this.OnIDDangThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangThuoc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDangThuoc
		{
			get
			{
				return this._TenDangThuoc;
			}
			set
			{
				if ((this._TenDangThuoc != value))
				{
					this.OnTenDangThuocChanging(value);
					this.SendPropertyChanging();
					this._TenDangThuoc = value;
					this.SendPropertyChanged("TenDangThuoc");
					this.OnTenDangThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_DangThuoc_w_NhanDangThuoc", Storage="_w_NhanDangThuocs", ThisKey="IDDangThuoc", OtherKey="IDDangThuoc")]
		public EntitySet<w_NhanDangThuoc> w_NhanDangThuocs
		{
			get
			{
				return this._w_NhanDangThuocs;
			}
			set
			{
				this._w_NhanDangThuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_w_NhanDangThuocs(w_NhanDangThuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_DangThuoc = this;
		}
		
		private void detach_w_NhanDangThuocs(w_NhanDangThuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_DangThuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_HinhAnhThuocChiTiet")]
	public partial class d_HinhAnhThuocChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDHinhAnh;
		
		private int _IDNhanDang;
		
		private string _DuongDanHinh;
		
		private string _MoTa;
		
		private EntityRef<w_NhanDangThuoc> _w_NhanDangThuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHinhAnhChanging(int value);
    partial void OnIDHinhAnhChanged();
    partial void OnIDNhanDangChanging(int value);
    partial void OnIDNhanDangChanged();
    partial void OnDuongDanHinhChanging(string value);
    partial void OnDuongDanHinhChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public d_HinhAnhThuocChiTiet()
		{
			this._w_NhanDangThuoc = default(EntityRef<w_NhanDangThuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHinhAnh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDHinhAnh
		{
			get
			{
				return this._IDHinhAnh;
			}
			set
			{
				if ((this._IDHinhAnh != value))
				{
					this.OnIDHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._IDHinhAnh = value;
					this.SendPropertyChanged("IDHinhAnh");
					this.OnIDHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhanDang", DbType="Int NOT NULL")]
		public int IDNhanDang
		{
			get
			{
				return this._IDNhanDang;
			}
			set
			{
				if ((this._IDNhanDang != value))
				{
					if (this._w_NhanDangThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDNhanDangChanging(value);
					this.SendPropertyChanging();
					this._IDNhanDang = value;
					this.SendPropertyChanged("IDNhanDang");
					this.OnIDNhanDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuongDanHinh", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DuongDanHinh
		{
			get
			{
				return this._DuongDanHinh;
			}
			set
			{
				if ((this._DuongDanHinh != value))
				{
					this.OnDuongDanHinhChanging(value);
					this.SendPropertyChanging();
					this._DuongDanHinh = value;
					this.SendPropertyChanged("DuongDanHinh");
					this.OnDuongDanHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(200)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="w_NhanDangThuoc_d_HinhAnhThuocChiTiet", Storage="_w_NhanDangThuoc", ThisKey="IDNhanDang", OtherKey="IDNhanDang", IsForeignKey=true)]
		public w_NhanDangThuoc w_NhanDangThuoc
		{
			get
			{
				return this._w_NhanDangThuoc.Entity;
			}
			set
			{
				w_NhanDangThuoc previousValue = this._w_NhanDangThuoc.Entity;
				if (((previousValue != value) 
							|| (this._w_NhanDangThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._w_NhanDangThuoc.Entity = null;
						previousValue.d_HinhAnhThuocChiTiets.Remove(this);
					}
					this._w_NhanDangThuoc.Entity = value;
					if ((value != null))
					{
						value.d_HinhAnhThuocChiTiets.Add(this);
						this._IDNhanDang = value.IDNhanDang;
					}
					else
					{
						this._IDNhanDang = default(int);
					}
					this.SendPropertyChanged("w_NhanDangThuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_HinhDang")]
	public partial class d_HinhDang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDHinhDang;
		
		private string _TenHinhDang;
		
		private EntitySet<w_NhanDangThuoc> _w_NhanDangThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHinhDangChanging(int value);
    partial void OnIDHinhDangChanged();
    partial void OnTenHinhDangChanging(string value);
    partial void OnTenHinhDangChanged();
    #endregion
		
		public d_HinhDang()
		{
			this._w_NhanDangThuocs = new EntitySet<w_NhanDangThuoc>(new Action<w_NhanDangThuoc>(this.attach_w_NhanDangThuocs), new Action<w_NhanDangThuoc>(this.detach_w_NhanDangThuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHinhDang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDHinhDang
		{
			get
			{
				return this._IDHinhDang;
			}
			set
			{
				if ((this._IDHinhDang != value))
				{
					this.OnIDHinhDangChanging(value);
					this.SendPropertyChanging();
					this._IDHinhDang = value;
					this.SendPropertyChanged("IDHinhDang");
					this.OnIDHinhDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHinhDang", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenHinhDang
		{
			get
			{
				return this._TenHinhDang;
			}
			set
			{
				if ((this._TenHinhDang != value))
				{
					this.OnTenHinhDangChanging(value);
					this.SendPropertyChanging();
					this._TenHinhDang = value;
					this.SendPropertyChanged("TenHinhDang");
					this.OnTenHinhDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_HinhDang_w_NhanDangThuoc", Storage="_w_NhanDangThuocs", ThisKey="IDHinhDang", OtherKey="IDHinhDang")]
		public EntitySet<w_NhanDangThuoc> w_NhanDangThuocs
		{
			get
			{
				return this._w_NhanDangThuocs;
			}
			set
			{
				this._w_NhanDangThuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_w_NhanDangThuocs(w_NhanDangThuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_HinhDang = this;
		}
		
		private void detach_w_NhanDangThuocs(w_NhanDangThuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_HinhDang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_HoatChat")]
	public partial class d_HoatChat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDHoatChat;
		
		private string _TenHoatChat;
		
		private string _LoaiHoatChat;
		
		private EntitySet<d_Thuoc> _d_Thuocs;
		
		private EntitySet<r_HoatChat_HoatChatGoc> _r_HoatChat_HoatChatGocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHoatChatChanging(int value);
    partial void OnIDHoatChatChanged();
    partial void OnTenHoatChatChanging(string value);
    partial void OnTenHoatChatChanged();
    partial void OnLoaiHoatChatChanging(string value);
    partial void OnLoaiHoatChatChanged();
    #endregion
		
		public d_HoatChat()
		{
			this._d_Thuocs = new EntitySet<d_Thuoc>(new Action<d_Thuoc>(this.attach_d_Thuocs), new Action<d_Thuoc>(this.detach_d_Thuocs));
			this._r_HoatChat_HoatChatGocs = new EntitySet<r_HoatChat_HoatChatGoc>(new Action<r_HoatChat_HoatChatGoc>(this.attach_r_HoatChat_HoatChatGocs), new Action<r_HoatChat_HoatChatGoc>(this.detach_r_HoatChat_HoatChatGocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHoatChat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDHoatChat
		{
			get
			{
				return this._IDHoatChat;
			}
			set
			{
				if ((this._IDHoatChat != value))
				{
					this.OnIDHoatChatChanging(value);
					this.SendPropertyChanging();
					this._IDHoatChat = value;
					this.SendPropertyChanged("IDHoatChat");
					this.OnIDHoatChatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHoatChat", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenHoatChat
		{
			get
			{
				return this._TenHoatChat;
			}
			set
			{
				if ((this._TenHoatChat != value))
				{
					this.OnTenHoatChatChanging(value);
					this.SendPropertyChanging();
					this._TenHoatChat = value;
					this.SendPropertyChanged("TenHoatChat");
					this.OnTenHoatChatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHoatChat", DbType="NVarChar(50)")]
		public string LoaiHoatChat
		{
			get
			{
				return this._LoaiHoatChat;
			}
			set
			{
				if ((this._LoaiHoatChat != value))
				{
					this.OnLoaiHoatChatChanging(value);
					this.SendPropertyChanging();
					this._LoaiHoatChat = value;
					this.SendPropertyChanged("LoaiHoatChat");
					this.OnLoaiHoatChatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_HoatChat_d_Thuoc", Storage="_d_Thuocs", ThisKey="IDHoatChat", OtherKey="IDHoatChat")]
		public EntitySet<d_Thuoc> d_Thuocs
		{
			get
			{
				return this._d_Thuocs;
			}
			set
			{
				this._d_Thuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_HoatChat_r_HoatChat_HoatChatGoc", Storage="_r_HoatChat_HoatChatGocs", ThisKey="IDHoatChat", OtherKey="IDHoatChat")]
		public EntitySet<r_HoatChat_HoatChatGoc> r_HoatChat_HoatChatGocs
		{
			get
			{
				return this._r_HoatChat_HoatChatGocs;
			}
			set
			{
				this._r_HoatChat_HoatChatGocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_d_Thuocs(d_Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_HoatChat = this;
		}
		
		private void detach_d_Thuocs(d_Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_HoatChat = null;
		}
		
		private void attach_r_HoatChat_HoatChatGocs(r_HoatChat_HoatChatGoc entity)
		{
			this.SendPropertyChanging();
			entity.d_HoatChat = this;
		}
		
		private void detach_r_HoatChat_HoatChatGocs(r_HoatChat_HoatChatGoc entity)
		{
			this.SendPropertyChanging();
			entity.d_HoatChat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_HoatChatGoc")]
	public partial class d_HoatChatGoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDHoatChatGoc;
		
		private string _TenHoatChat;
		
		private string _GhiChu;
		
		private EntitySet<r_HoatChat_HoatChatGoc> _r_HoatChat_HoatChatGocs;
		
		private EntitySet<r_HoatChatGoc_ChiDinh> _r_HoatChatGoc_ChiDinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHoatChatGocChanging(int value);
    partial void OnIDHoatChatGocChanged();
    partial void OnTenHoatChatChanging(string value);
    partial void OnTenHoatChatChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public d_HoatChatGoc()
		{
			this._r_HoatChat_HoatChatGocs = new EntitySet<r_HoatChat_HoatChatGoc>(new Action<r_HoatChat_HoatChatGoc>(this.attach_r_HoatChat_HoatChatGocs), new Action<r_HoatChat_HoatChatGoc>(this.detach_r_HoatChat_HoatChatGocs));
			this._r_HoatChatGoc_ChiDinhs = new EntitySet<r_HoatChatGoc_ChiDinh>(new Action<r_HoatChatGoc_ChiDinh>(this.attach_r_HoatChatGoc_ChiDinhs), new Action<r_HoatChatGoc_ChiDinh>(this.detach_r_HoatChatGoc_ChiDinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHoatChatGoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDHoatChatGoc
		{
			get
			{
				return this._IDHoatChatGoc;
			}
			set
			{
				if ((this._IDHoatChatGoc != value))
				{
					this.OnIDHoatChatGocChanging(value);
					this.SendPropertyChanging();
					this._IDHoatChatGoc = value;
					this.SendPropertyChanged("IDHoatChatGoc");
					this.OnIDHoatChatGocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHoatChat", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenHoatChat
		{
			get
			{
				return this._TenHoatChat;
			}
			set
			{
				if ((this._TenHoatChat != value))
				{
					this.OnTenHoatChatChanging(value);
					this.SendPropertyChanging();
					this._TenHoatChat = value;
					this.SendPropertyChanged("TenHoatChat");
					this.OnTenHoatChatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_HoatChatGoc_r_HoatChat_HoatChatGoc", Storage="_r_HoatChat_HoatChatGocs", ThisKey="IDHoatChatGoc", OtherKey="IDHoatChatGoc")]
		public EntitySet<r_HoatChat_HoatChatGoc> r_HoatChat_HoatChatGocs
		{
			get
			{
				return this._r_HoatChat_HoatChatGocs;
			}
			set
			{
				this._r_HoatChat_HoatChatGocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_HoatChatGoc_r_HoatChatGoc_ChiDinh", Storage="_r_HoatChatGoc_ChiDinhs", ThisKey="IDHoatChatGoc", OtherKey="IDHoatChatGoc")]
		public EntitySet<r_HoatChatGoc_ChiDinh> r_HoatChatGoc_ChiDinhs
		{
			get
			{
				return this._r_HoatChatGoc_ChiDinhs;
			}
			set
			{
				this._r_HoatChatGoc_ChiDinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_r_HoatChat_HoatChatGocs(r_HoatChat_HoatChatGoc entity)
		{
			this.SendPropertyChanging();
			entity.d_HoatChatGoc = this;
		}
		
		private void detach_r_HoatChat_HoatChatGocs(r_HoatChat_HoatChatGoc entity)
		{
			this.SendPropertyChanging();
			entity.d_HoatChatGoc = null;
		}
		
		private void attach_r_HoatChatGoc_ChiDinhs(r_HoatChatGoc_ChiDinh entity)
		{
			this.SendPropertyChanging();
			entity.d_HoatChatGoc = this;
		}
		
		private void detach_r_HoatChatGoc_ChiDinhs(r_HoatChatGoc_ChiDinh entity)
		{
			this.SendPropertyChanging();
			entity.d_HoatChatGoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_LoaiRanh")]
	public partial class d_LoaiRanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDLoaiRanh;
		
		private string _TenLoaiRanh;
		
		private EntitySet<w_NhanDangThuoc> _w_NhanDangThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDLoaiRanhChanging(int value);
    partial void OnIDLoaiRanhChanged();
    partial void OnTenLoaiRanhChanging(string value);
    partial void OnTenLoaiRanhChanged();
    #endregion
		
		public d_LoaiRanh()
		{
			this._w_NhanDangThuocs = new EntitySet<w_NhanDangThuoc>(new Action<w_NhanDangThuoc>(this.attach_w_NhanDangThuocs), new Action<w_NhanDangThuoc>(this.detach_w_NhanDangThuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLoaiRanh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDLoaiRanh
		{
			get
			{
				return this._IDLoaiRanh;
			}
			set
			{
				if ((this._IDLoaiRanh != value))
				{
					this.OnIDLoaiRanhChanging(value);
					this.SendPropertyChanging();
					this._IDLoaiRanh = value;
					this.SendPropertyChanged("IDLoaiRanh");
					this.OnIDLoaiRanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiRanh", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLoaiRanh
		{
			get
			{
				return this._TenLoaiRanh;
			}
			set
			{
				if ((this._TenLoaiRanh != value))
				{
					this.OnTenLoaiRanhChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiRanh = value;
					this.SendPropertyChanged("TenLoaiRanh");
					this.OnTenLoaiRanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_LoaiRanh_w_NhanDangThuoc", Storage="_w_NhanDangThuocs", ThisKey="IDLoaiRanh", OtherKey="IDLoaiRanh")]
		public EntitySet<w_NhanDangThuoc> w_NhanDangThuocs
		{
			get
			{
				return this._w_NhanDangThuocs;
			}
			set
			{
				this._w_NhanDangThuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_w_NhanDangThuocs(w_NhanDangThuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_LoaiRanh = this;
		}
		
		private void detach_w_NhanDangThuocs(w_NhanDangThuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_LoaiRanh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_LoaiViThuoc")]
	public partial class d_LoaiViThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDLoaiViThuoc;
		
		private string _TenLoaiVi;
		
		private EntitySet<w_NhanDangThuoc> _w_NhanDangThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDLoaiViThuocChanging(int value);
    partial void OnIDLoaiViThuocChanged();
    partial void OnTenLoaiViChanging(string value);
    partial void OnTenLoaiViChanged();
    #endregion
		
		public d_LoaiViThuoc()
		{
			this._w_NhanDangThuocs = new EntitySet<w_NhanDangThuoc>(new Action<w_NhanDangThuoc>(this.attach_w_NhanDangThuocs), new Action<w_NhanDangThuoc>(this.detach_w_NhanDangThuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLoaiViThuoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDLoaiViThuoc
		{
			get
			{
				return this._IDLoaiViThuoc;
			}
			set
			{
				if ((this._IDLoaiViThuoc != value))
				{
					this.OnIDLoaiViThuocChanging(value);
					this.SendPropertyChanging();
					this._IDLoaiViThuoc = value;
					this.SendPropertyChanged("IDLoaiViThuoc");
					this.OnIDLoaiViThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiVi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLoaiVi
		{
			get
			{
				return this._TenLoaiVi;
			}
			set
			{
				if ((this._TenLoaiVi != value))
				{
					this.OnTenLoaiViChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiVi = value;
					this.SendPropertyChanged("TenLoaiVi");
					this.OnTenLoaiViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_LoaiViThuoc_w_NhanDangThuoc", Storage="_w_NhanDangThuocs", ThisKey="IDLoaiViThuoc", OtherKey="IDLoaiViThuoc")]
		public EntitySet<w_NhanDangThuoc> w_NhanDangThuocs
		{
			get
			{
				return this._w_NhanDangThuocs;
			}
			set
			{
				this._w_NhanDangThuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_w_NhanDangThuocs(w_NhanDangThuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_LoaiViThuoc = this;
		}
		
		private void detach_w_NhanDangThuocs(w_NhanDangThuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_LoaiViThuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_MauSac")]
	public partial class d_MauSac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDMauSac;
		
		private string _TenMauSac;
		
		private EntitySet<r_Thuoc_MauSac> _r_Thuoc_MauSacs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDMauSacChanging(int value);
    partial void OnIDMauSacChanged();
    partial void OnTenMauSacChanging(string value);
    partial void OnTenMauSacChanged();
    #endregion
		
		public d_MauSac()
		{
			this._r_Thuoc_MauSacs = new EntitySet<r_Thuoc_MauSac>(new Action<r_Thuoc_MauSac>(this.attach_r_Thuoc_MauSacs), new Action<r_Thuoc_MauSac>(this.detach_r_Thuoc_MauSacs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMauSac", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDMauSac
		{
			get
			{
				return this._IDMauSac;
			}
			set
			{
				if ((this._IDMauSac != value))
				{
					this.OnIDMauSacChanging(value);
					this.SendPropertyChanging();
					this._IDMauSac = value;
					this.SendPropertyChanged("IDMauSac");
					this.OnIDMauSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMauSac", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenMauSac
		{
			get
			{
				return this._TenMauSac;
			}
			set
			{
				if ((this._TenMauSac != value))
				{
					this.OnTenMauSacChanging(value);
					this.SendPropertyChanging();
					this._TenMauSac = value;
					this.SendPropertyChanged("TenMauSac");
					this.OnTenMauSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_MauSac_r_Thuoc_MauSac", Storage="_r_Thuoc_MauSacs", ThisKey="IDMauSac", OtherKey="IDMauSac")]
		public EntitySet<r_Thuoc_MauSac> r_Thuoc_MauSacs
		{
			get
			{
				return this._r_Thuoc_MauSacs;
			}
			set
			{
				this._r_Thuoc_MauSacs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_r_Thuoc_MauSacs(r_Thuoc_MauSac entity)
		{
			this.SendPropertyChanging();
			entity.d_MauSac = this;
		}
		
		private void detach_r_Thuoc_MauSacs(r_Thuoc_MauSac entity)
		{
			this.SendPropertyChanging();
			entity.d_MauSac = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.d_Thuoc")]
	public partial class d_Thuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDThuoc;
		
		private string _TenThuoc;
		
		private string _SDK;
		
		private System.Nullable<int> _IDHoatChat;
		
		private string _HamLuong;
		
		private string _DangBaoChe;
		
		private string _NhaSX;
		
		private string _GhiChu;
		
		private EntitySet<w_NhanDangThuoc> _w_NhanDangThuocs;
		
		private EntitySet<r_Thuoc_MauSac> _r_Thuoc_MauSacs;
		
		private EntityRef<d_HoatChat> _d_HoatChat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDThuocChanging(int value);
    partial void OnIDThuocChanged();
    partial void OnTenThuocChanging(string value);
    partial void OnTenThuocChanged();
    partial void OnSDKChanging(string value);
    partial void OnSDKChanged();
    partial void OnIDHoatChatChanging(System.Nullable<int> value);
    partial void OnIDHoatChatChanged();
    partial void OnHamLuongChanging(string value);
    partial void OnHamLuongChanged();
    partial void OnDangBaoCheChanging(string value);
    partial void OnDangBaoCheChanged();
    partial void OnNhaSXChanging(string value);
    partial void OnNhaSXChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public d_Thuoc()
		{
			this._w_NhanDangThuocs = new EntitySet<w_NhanDangThuoc>(new Action<w_NhanDangThuoc>(this.attach_w_NhanDangThuocs), new Action<w_NhanDangThuoc>(this.detach_w_NhanDangThuocs));
			this._r_Thuoc_MauSacs = new EntitySet<r_Thuoc_MauSac>(new Action<r_Thuoc_MauSac>(this.attach_r_Thuoc_MauSacs), new Action<r_Thuoc_MauSac>(this.detach_r_Thuoc_MauSacs));
			this._d_HoatChat = default(EntityRef<d_HoatChat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThuoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDThuoc
		{
			get
			{
				return this._IDThuoc;
			}
			set
			{
				if ((this._IDThuoc != value))
				{
					this.OnIDThuocChanging(value);
					this.SendPropertyChanging();
					this._IDThuoc = value;
					this.SendPropertyChanged("IDThuoc");
					this.OnIDThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuoc", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenThuoc
		{
			get
			{
				return this._TenThuoc;
			}
			set
			{
				if ((this._TenThuoc != value))
				{
					this.OnTenThuocChanging(value);
					this.SendPropertyChanging();
					this._TenThuoc = value;
					this.SendPropertyChanged("TenThuoc");
					this.OnTenThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDK", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SDK
		{
			get
			{
				return this._SDK;
			}
			set
			{
				if ((this._SDK != value))
				{
					this.OnSDKChanging(value);
					this.SendPropertyChanging();
					this._SDK = value;
					this.SendPropertyChanged("SDK");
					this.OnSDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHoatChat", DbType="Int")]
		public System.Nullable<int> IDHoatChat
		{
			get
			{
				return this._IDHoatChat;
			}
			set
			{
				if ((this._IDHoatChat != value))
				{
					if (this._d_HoatChat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDHoatChatChanging(value);
					this.SendPropertyChanging();
					this._IDHoatChat = value;
					this.SendPropertyChanged("IDHoatChat");
					this.OnIDHoatChatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HamLuong", DbType="NVarChar(100)")]
		public string HamLuong
		{
			get
			{
				return this._HamLuong;
			}
			set
			{
				if ((this._HamLuong != value))
				{
					this.OnHamLuongChanging(value);
					this.SendPropertyChanging();
					this._HamLuong = value;
					this.SendPropertyChanged("HamLuong");
					this.OnHamLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangBaoChe", DbType="NVarChar(100)")]
		public string DangBaoChe
		{
			get
			{
				return this._DangBaoChe;
			}
			set
			{
				if ((this._DangBaoChe != value))
				{
					this.OnDangBaoCheChanging(value);
					this.SendPropertyChanging();
					this._DangBaoChe = value;
					this.SendPropertyChanged("DangBaoChe");
					this.OnDangBaoCheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaSX", DbType="NVarChar(200)")]
		public string NhaSX
		{
			get
			{
				return this._NhaSX;
			}
			set
			{
				if ((this._NhaSX != value))
				{
					this.OnNhaSXChanging(value);
					this.SendPropertyChanging();
					this._NhaSX = value;
					this.SendPropertyChanged("NhaSX");
					this.OnNhaSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thuoc_w_NhanDangThuoc", Storage="_w_NhanDangThuocs", ThisKey="IDThuoc", OtherKey="IDThuoc")]
		public EntitySet<w_NhanDangThuoc> w_NhanDangThuocs
		{
			get
			{
				return this._w_NhanDangThuocs;
			}
			set
			{
				this._w_NhanDangThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thuoc_r_Thuoc_MauSac", Storage="_r_Thuoc_MauSacs", ThisKey="IDThuoc", OtherKey="IDThuoc")]
		public EntitySet<r_Thuoc_MauSac> r_Thuoc_MauSacs
		{
			get
			{
				return this._r_Thuoc_MauSacs;
			}
			set
			{
				this._r_Thuoc_MauSacs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_HoatChat_d_Thuoc", Storage="_d_HoatChat", ThisKey="IDHoatChat", OtherKey="IDHoatChat", IsForeignKey=true)]
		public d_HoatChat d_HoatChat
		{
			get
			{
				return this._d_HoatChat.Entity;
			}
			set
			{
				d_HoatChat previousValue = this._d_HoatChat.Entity;
				if (((previousValue != value) 
							|| (this._d_HoatChat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_HoatChat.Entity = null;
						previousValue.d_Thuocs.Remove(this);
					}
					this._d_HoatChat.Entity = value;
					if ((value != null))
					{
						value.d_Thuocs.Add(this);
						this._IDHoatChat = value.IDHoatChat;
					}
					else
					{
						this._IDHoatChat = default(Nullable<int>);
					}
					this.SendPropertyChanged("d_HoatChat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_w_NhanDangThuocs(w_NhanDangThuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_Thuoc = this;
		}
		
		private void detach_w_NhanDangThuocs(w_NhanDangThuoc entity)
		{
			this.SendPropertyChanging();
			entity.d_Thuoc = null;
		}
		
		private void attach_r_Thuoc_MauSacs(r_Thuoc_MauSac entity)
		{
			this.SendPropertyChanging();
			entity.d_Thuoc = this;
		}
		
		private void detach_r_Thuoc_MauSacs(r_Thuoc_MauSac entity)
		{
			this.SendPropertyChanging();
			entity.d_Thuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.r_HoatChat_HoatChatGoc")]
	public partial class r_HoatChat_HoatChatGoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDHoatChat;
		
		private int _IDHoatChatGoc;
		
		private EntityRef<d_HoatChat> _d_HoatChat;
		
		private EntityRef<d_HoatChatGoc> _d_HoatChatGoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHoatChatChanging(int value);
    partial void OnIDHoatChatChanged();
    partial void OnIDHoatChatGocChanging(int value);
    partial void OnIDHoatChatGocChanged();
    #endregion
		
		public r_HoatChat_HoatChatGoc()
		{
			this._d_HoatChat = default(EntityRef<d_HoatChat>);
			this._d_HoatChatGoc = default(EntityRef<d_HoatChatGoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHoatChat", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDHoatChat
		{
			get
			{
				return this._IDHoatChat;
			}
			set
			{
				if ((this._IDHoatChat != value))
				{
					if (this._d_HoatChat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDHoatChatChanging(value);
					this.SendPropertyChanging();
					this._IDHoatChat = value;
					this.SendPropertyChanged("IDHoatChat");
					this.OnIDHoatChatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHoatChatGoc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDHoatChatGoc
		{
			get
			{
				return this._IDHoatChatGoc;
			}
			set
			{
				if ((this._IDHoatChatGoc != value))
				{
					if (this._d_HoatChatGoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDHoatChatGocChanging(value);
					this.SendPropertyChanging();
					this._IDHoatChatGoc = value;
					this.SendPropertyChanged("IDHoatChatGoc");
					this.OnIDHoatChatGocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_HoatChat_r_HoatChat_HoatChatGoc", Storage="_d_HoatChat", ThisKey="IDHoatChat", OtherKey="IDHoatChat", IsForeignKey=true)]
		public d_HoatChat d_HoatChat
		{
			get
			{
				return this._d_HoatChat.Entity;
			}
			set
			{
				d_HoatChat previousValue = this._d_HoatChat.Entity;
				if (((previousValue != value) 
							|| (this._d_HoatChat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_HoatChat.Entity = null;
						previousValue.r_HoatChat_HoatChatGocs.Remove(this);
					}
					this._d_HoatChat.Entity = value;
					if ((value != null))
					{
						value.r_HoatChat_HoatChatGocs.Add(this);
						this._IDHoatChat = value.IDHoatChat;
					}
					else
					{
						this._IDHoatChat = default(int);
					}
					this.SendPropertyChanged("d_HoatChat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_HoatChatGoc_r_HoatChat_HoatChatGoc", Storage="_d_HoatChatGoc", ThisKey="IDHoatChatGoc", OtherKey="IDHoatChatGoc", IsForeignKey=true)]
		public d_HoatChatGoc d_HoatChatGoc
		{
			get
			{
				return this._d_HoatChatGoc.Entity;
			}
			set
			{
				d_HoatChatGoc previousValue = this._d_HoatChatGoc.Entity;
				if (((previousValue != value) 
							|| (this._d_HoatChatGoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_HoatChatGoc.Entity = null;
						previousValue.r_HoatChat_HoatChatGocs.Remove(this);
					}
					this._d_HoatChatGoc.Entity = value;
					if ((value != null))
					{
						value.r_HoatChat_HoatChatGocs.Add(this);
						this._IDHoatChatGoc = value.IDHoatChatGoc;
					}
					else
					{
						this._IDHoatChatGoc = default(int);
					}
					this.SendPropertyChanged("d_HoatChatGoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.r_HoatChatGoc_ChiDinh")]
	public partial class r_HoatChatGoc_ChiDinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDHoatChatGoc;
		
		private int _IDChiDinh;
		
		private EntityRef<d_ChiDinh> _d_ChiDinh;
		
		private EntityRef<d_HoatChatGoc> _d_HoatChatGoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHoatChatGocChanging(int value);
    partial void OnIDHoatChatGocChanged();
    partial void OnIDChiDinhChanging(int value);
    partial void OnIDChiDinhChanged();
    #endregion
		
		public r_HoatChatGoc_ChiDinh()
		{
			this._d_ChiDinh = default(EntityRef<d_ChiDinh>);
			this._d_HoatChatGoc = default(EntityRef<d_HoatChatGoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHoatChatGoc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDHoatChatGoc
		{
			get
			{
				return this._IDHoatChatGoc;
			}
			set
			{
				if ((this._IDHoatChatGoc != value))
				{
					if (this._d_HoatChatGoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDHoatChatGocChanging(value);
					this.SendPropertyChanging();
					this._IDHoatChatGoc = value;
					this.SendPropertyChanged("IDHoatChatGoc");
					this.OnIDHoatChatGocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChiDinh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDChiDinh
		{
			get
			{
				return this._IDChiDinh;
			}
			set
			{
				if ((this._IDChiDinh != value))
				{
					if (this._d_ChiDinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChiDinhChanging(value);
					this.SendPropertyChanging();
					this._IDChiDinh = value;
					this.SendPropertyChanged("IDChiDinh");
					this.OnIDChiDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_ChiDinh_r_HoatChatGoc_ChiDinh", Storage="_d_ChiDinh", ThisKey="IDChiDinh", OtherKey="IDChiDinh", IsForeignKey=true)]
		public d_ChiDinh d_ChiDinh
		{
			get
			{
				return this._d_ChiDinh.Entity;
			}
			set
			{
				d_ChiDinh previousValue = this._d_ChiDinh.Entity;
				if (((previousValue != value) 
							|| (this._d_ChiDinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_ChiDinh.Entity = null;
						previousValue.r_HoatChatGoc_ChiDinhs.Remove(this);
					}
					this._d_ChiDinh.Entity = value;
					if ((value != null))
					{
						value.r_HoatChatGoc_ChiDinhs.Add(this);
						this._IDChiDinh = value.IDChiDinh;
					}
					else
					{
						this._IDChiDinh = default(int);
					}
					this.SendPropertyChanged("d_ChiDinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_HoatChatGoc_r_HoatChatGoc_ChiDinh", Storage="_d_HoatChatGoc", ThisKey="IDHoatChatGoc", OtherKey="IDHoatChatGoc", IsForeignKey=true)]
		public d_HoatChatGoc d_HoatChatGoc
		{
			get
			{
				return this._d_HoatChatGoc.Entity;
			}
			set
			{
				d_HoatChatGoc previousValue = this._d_HoatChatGoc.Entity;
				if (((previousValue != value) 
							|| (this._d_HoatChatGoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_HoatChatGoc.Entity = null;
						previousValue.r_HoatChatGoc_ChiDinhs.Remove(this);
					}
					this._d_HoatChatGoc.Entity = value;
					if ((value != null))
					{
						value.r_HoatChatGoc_ChiDinhs.Add(this);
						this._IDHoatChatGoc = value.IDHoatChatGoc;
					}
					else
					{
						this._IDHoatChatGoc = default(int);
					}
					this.SendPropertyChanged("d_HoatChatGoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.r_Thuoc_MauSac")]
	public partial class r_Thuoc_MauSac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDThuoc;
		
		private int _IDMauSac;
		
		private EntityRef<d_MauSac> _d_MauSac;
		
		private EntityRef<d_Thuoc> _d_Thuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDThuocChanging(int value);
    partial void OnIDThuocChanged();
    partial void OnIDMauSacChanging(int value);
    partial void OnIDMauSacChanged();
    #endregion
		
		public r_Thuoc_MauSac()
		{
			this._d_MauSac = default(EntityRef<d_MauSac>);
			this._d_Thuoc = default(EntityRef<d_Thuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDThuoc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDThuoc
		{
			get
			{
				return this._IDThuoc;
			}
			set
			{
				if ((this._IDThuoc != value))
				{
					if (this._d_Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDThuocChanging(value);
					this.SendPropertyChanging();
					this._IDThuoc = value;
					this.SendPropertyChanged("IDThuoc");
					this.OnIDThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMauSac", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDMauSac
		{
			get
			{
				return this._IDMauSac;
			}
			set
			{
				if ((this._IDMauSac != value))
				{
					if (this._d_MauSac.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDMauSacChanging(value);
					this.SendPropertyChanging();
					this._IDMauSac = value;
					this.SendPropertyChanged("IDMauSac");
					this.OnIDMauSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_MauSac_r_Thuoc_MauSac", Storage="_d_MauSac", ThisKey="IDMauSac", OtherKey="IDMauSac", IsForeignKey=true)]
		public d_MauSac d_MauSac
		{
			get
			{
				return this._d_MauSac.Entity;
			}
			set
			{
				d_MauSac previousValue = this._d_MauSac.Entity;
				if (((previousValue != value) 
							|| (this._d_MauSac.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_MauSac.Entity = null;
						previousValue.r_Thuoc_MauSacs.Remove(this);
					}
					this._d_MauSac.Entity = value;
					if ((value != null))
					{
						value.r_Thuoc_MauSacs.Add(this);
						this._IDMauSac = value.IDMauSac;
					}
					else
					{
						this._IDMauSac = default(int);
					}
					this.SendPropertyChanged("d_MauSac");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="d_Thuoc_r_Thuoc_MauSac", Storage="_d_Thuoc", ThisKey="IDThuoc", OtherKey="IDThuoc", IsForeignKey=true)]
		public d_Thuoc d_Thuoc
		{
			get
			{
				return this._d_Thuoc.Entity;
			}
			set
			{
				d_Thuoc previousValue = this._d_Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._d_Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._d_Thuoc.Entity = null;
						previousValue.r_Thuoc_MauSacs.Remove(this);
					}
					this._d_Thuoc.Entity = value;
					if ((value != null))
					{
						value.r_Thuoc_MauSacs.Add(this);
						this._IDThuoc = value.IDThuoc;
					}
					else
					{
						this._IDThuoc = default(int);
					}
					this.SendPropertyChanged("d_Thuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
